### ISSUE TITLE
Failed to modify wsURL

### ISSUE THREAD

**Issue by frenchmustard** [igolaizola/igogpt#1]
Hi, just installed iGoGPT and made a simple igogpt.yaml and it gives me the following error when running the command "igogpt auto --config igogpt.yaml":
`igogpt: couldn't create chatgpt client: could not disable webdriver: failed to modify wsURL: Get "http://localhost:9222/json/version": dial tcp [::1]:9222: connectex: No connection could be made because the target machine actively refused it.`

My igogpt.yaml file looks like this:
`# igogpt.yaml
model: gpt-3.5-turbo
openai-key: [REDACTED]
google-key: 
google-cx: 
chatgpt-remote: http://localhost:9222
bing-session: bing-session.yaml
goal: |
    Implement a hello world program in Go in different languages.
    The program takes the language as a parameter.`

I left some keys empty, maybe this is the issue (i.e. trying to use certain sources when they are not defined in the .yaml/env)?

**Comment by frenchmustard** [comment]
The function returning "failed to modify wsURL" is not from your package btw, it is from [chromedp's Allocate function](https://github.com/chromedp/chromedp/blob/master/allocate.go).

**Comment by igolaizola** [comment]
Hi @frenchmustard! Could you check that you have access to "http://localhost:9222/json/version" from the same terminal where you are launching `igogpt`? You can run a curl command to check it:
```
curl http://localhost:9222/json/version
```
If you are running igogpt from WSL and the browser on windows you may have problems.
An easy fix is to use ngrok, as I mention in the FAQ section of the readme.

**Comment by frenchmustard** [comment]
Nevermind! I launched it without the browser which is why it didn't work, it works now. However, I thought the browser was unnecessary if supplied with the OpenAI key in the .yaml, do I need to remove the `chatgpt-remote` key from the .yaml in order for it to use solely the API?

**Comment by igolaizola** [comment]
If you use `ai: openai` you can leave `chatgpt-remote` unset.
