### ISSUE TITLE
"google-chrome": executable file not found in $PATH

### ISSUE THREAD

**Issue by sohaha** [igolaizola/igogpt#3]
Is it compatible with Microsoft Edge, with the addition that I am testing on MacOS?

**Comment by igolaizola** [comment]
You should be able to use it with Edge and MacOS.
I suppose you want to run it with `ai: chatgpt`.

You can run Edge in debug mode with something like this (I haven't tested it because I don't own a macos):
```
"/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge" --remote-debugging-port=9222 --user-data-dir=~/EdgeDebug
```

And then using `chatgpt-remote: https://localhost:9222` in your config file.

**Comment by sohaha** [comment]
Actually, I am using OpenAI, thank you for your help.
